[tool.poetry]
name = "binance_test_task"
version = "0.0.1"
description = "Test task for Cindicator"
authors = ["Victoria Shepard <jawektor37@gmail.com>]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.black]
line-length = 120
target_version = ["py38"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"