name: code-quality

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install binance
        pip install poetry
        poetry install --no-interaction
        poetry run pip3 install  'mypy <0.800'
    - name: Code quality
      run: |
        set +e
        poetry run mypy --html-report mypy-report binance_test_task; MYPY_CODE=$?
        if [[ $MYPY_CODE -ne 0 ]]; then
          echo "SOME CHECKS HAVE FAILED"
          exit 1
        fi
        set -e